#!/usr/bin/env bash
#
# Assemble favro-mcp.plugin — a single multi-arch zip that registers the
# favro-mcp binary as an MCP server in a Claude Code / Cowork profile.
#
# Inputs:
#   dist/                produced by `goreleaser release` or
#                        `goreleaser release --snapshot --clean --skip=publish`.
#                        Reads the binary paths and version from
#                        dist/artifacts.json + dist/metadata.json so this
#                        script doesn't duplicate goreleaser's path-template
#                        knowledge.
#   plugin-template/     manifest + .mcp.json with placeholder version.
#
# Output: ./favro-mcp.plugin in the repo root.

set -euo pipefail

cd "$(dirname "$0")/.."

DIST="${DIST:-dist}"
TEMPLATE_DIR="plugin-template"
STAGING="$DIST/.plugin-staging"
ARTIFACT="favro-mcp.plugin"

if [ ! -f "$DIST/artifacts.json" ] || [ ! -f "$DIST/metadata.json" ]; then
    echo "package-plugin: $DIST/artifacts.json or $DIST/metadata.json not found." >&2
    echo "                Run 'goreleaser release' or" >&2
    echo "                'goreleaser release --snapshot --clean --skip=publish' first." >&2
    exit 1
fi

if [ ! -d "$TEMPLATE_DIR" ]; then
    echo "package-plugin: $TEMPLATE_DIR not found." >&2
    exit 1
fi

VERSION="$(jq -r '.version' "$DIST/metadata.json")"
if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
    echo "package-plugin: could not read .version from $DIST/metadata.json" >&2
    exit 1
fi

echo "package-plugin: assembling $ARTIFACT for version $VERSION"

rm -rf "$STAGING"
mkdir -p "$STAGING/.claude-plugin" "$STAGING/bin"

# Manifest with the goreleaser version substituted in. jq --arg avoids the
# shell-quoting hazards of sed substitution and re-emits a clean JSON document.
jq --arg v "$VERSION" '.version = $v' \
    "$TEMPLATE_DIR/.claude-plugin/plugin.json" \
    > "$STAGING/.claude-plugin/plugin.json"

# Plugin-variant .mcp.json (uses ${CLAUDE_PLUGIN_ROOT}, distinct from any
# local-dev .mcp.json that may live at the repo root).
cp "$TEMPLATE_DIR/.mcp.json" "$STAGING/.mcp.json"

# Copy each cross-built binary into bin/<goos>-<goarch>/.
jq -r '.[] | select(.type == "Binary") | "\(.path)\t\(.goos)-\(.goarch)\t\(.name)"' \
    "$DIST/artifacts.json" |
while IFS=$'\t' read -r src arch_dir bin_name; do
    install -Dm755 "$src" "$STAGING/bin/$arch_dir/$bin_name"
done

# Bash launcher shim that picks the right arch binary on macOS / Linux.
# Windows hosts use the .cmd shim below instead — they resolve
# bin/favro-mcp via PATHEXT (.COM;.EXE;.BAT;.CMD;...).
cat > "$STAGING/bin/favro-mcp" <<'LAUNCHER'
#!/usr/bin/env bash
# Auto-generated by scripts/package-plugin.sh. Do not edit.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
case "$(uname -s)-$(uname -m)" in
    Darwin-arm64)              exec "$here/darwin-arm64/favro-mcp" "$@" ;;
    Darwin-x86_64)             exec "$here/darwin-amd64/favro-mcp" "$@" ;;
    Linux-x86_64)              exec "$here/linux-amd64/favro-mcp" "$@" ;;
    Linux-aarch64|Linux-arm64) exec "$here/linux-arm64/favro-mcp" "$@" ;;
    *)
        echo "favro-mcp: unsupported platform $(uname -s)-$(uname -m); on Windows the .cmd shim should run instead." >&2
        exit 1
        ;;
esac
LAUNCHER
chmod +x "$STAGING/bin/favro-mcp"

# Windows launcher shim. Only one Windows arch ships in the bundle
# (windows-amd64; windows-arm64 is `ignored:` in .goreleaser.yaml), so no
# arch detection is needed. %~dp0 resolves to the .cmd's own directory
# (with trailing backslash) — keeps the shim relocatable. Uses CRLF line
# endings so cmd.exe parses it correctly even when the .plugin zip is
# extracted on a Unix host first.
printf '@echo off\r\n"%%~dp0windows-amd64\\favro-mcp.exe" %%*\r\n' \
    > "$STAGING/bin/favro-mcp.cmd"

# Bundle docs + license metadata.
cp LICENSE NOTICE README.md "$STAGING/"

# Zip with deterministic ordering so identical inputs produce identical
# bytes — useful for verifying release artifact reproducibility.
rm -f "$ARTIFACT"
( cd "$STAGING" && find . -type f -print0 | LC_ALL=C sort -z | xargs -0 zip -X -q "$OLDPWD/$ARTIFACT" )

echo "package-plugin: produced $ARTIFACT"
ls -la "$ARTIFACT"
